import React, { useEffect, useState, useMemo } from "react";
import axios from "axios";
import { 
  FiSearch, FiDownload, FiUsers, FiCheckCircle, 
  FiXCircle, FiRefreshCw, FiActivity, FiLayers, FiClock, 
  FiEdit2, FiSave, FiX, FiCommand, FiFileText, FiServer, FiShield
} from "react-icons/fi";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const AdminDashboard = () => {
  const [students, setStudents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [editingStudent, setEditingStudent] = useState(null);
  const [editingStatus, setEditingStatus] = useState("");
  const [currentTime, setCurrentTime] = useState(new Date());

  useEffect(() => {
    const link = document.createElement('link');
    link.href = 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap';
    link.rel = 'stylesheet';
    document.head.appendChild(link);
    loadUsers();
    const timer = setInterval(() => setCurrentTime(new Date()), 1000);
    return () => clearInterval(timer);
  }, []);

  const loadUsers = async () => {
    setLoading(true);
    try {
      const res = await axios.get("http://localhost:5001/api/auth/users", { withCredentials: true });
      setStudents(res.data.data);
    } catch (err) {
      console.error("Fetch error:", err);
    } finally {
      setLoading(false);
    }
  };

  // --- ENHANCED PDF EXPORT ---
  const exportToPDF = () => {
    const doc = new jsPDF();
    
    // Header Branding
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(20, 30, 70);
    doc.text("Dr. Mahalingam College of Engineering and Technology", 105, 20, { align: "center" });
    
    doc.setFontSize(14);
    doc.setTextColor(67, 24, 255);
    doc.text("ECE Department Association - SPECTRUM", 105, 30, { align: "center" });
    
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 35, 190, 35);

    // Metadata
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.setFont("helvetica", "normal");
    doc.text(`Report Type: Attendance Verification`, 20, 45);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 190, 45, { align: "right" });

    const tableColumn = ["Roll No", "Student Name", "Class", "Status", "Last Log"];
    const tableRows = filteredStudents.map(s => [
      s.rollNo,
      s.name,
      s.className,
      s.hasAttended ? "PRESENT" : "ABSENT",
      s.attendedAt ? new Date(s.attendedAt).toLocaleTimeString() : "N/A"
    ]);

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 50,
      theme: 'striped',
      headStyles: { fillColor: [43, 54, 116], textColor: [255, 255, 255], fontStyle: 'bold' },
      styles: { font: 'helvetica', fontSize: 9 },
      columnStyles: {
        3: { fontStyle: 'bold' }
      }
    });

    // Footer
    const finalY = doc.lastAutoTable.finalY || 50;
    doc.setFontSize(8);
    doc.text("Generated by SPECTRUM System Integrity Module", 105, finalY + 20, { align: "center" });

    doc.save(`SPECTRUM_Attendance_${new Date().toLocaleDateString()}.pdf`);
  };

  const updateAttendance = async (studentId, newStatus) => {
    try {
      await axios.patch(
        `http://localhost:5001/api/auth/users/${studentId}/attendance`,
        { hasAttended: newStatus === "present" },
        { withCredentials: true }
      );
      setStudents(prev => prev.map(s => 
        s._id === studentId ? { ...s, hasAttended: newStatus === "present", attendedAt: new Date().toISOString() } : s
      ));
      setEditingStudent(null);
    } catch (err) { console.error(err); }
  };

  const filteredStudents = students.filter(s => {
    const matchesSearch = s.name?.toLowerCase().includes(search.toLowerCase()) || s.rollNo?.toLowerCase().includes(search.toLowerCase());
    const matchesStatus = statusFilter === "all" || (statusFilter === "present" ? s.hasAttended : !s.hasAttended);
    return matchesSearch && matchesStatus;
  });

  const stats = useMemo(() => {
    const total = students.length;
    const present = students.filter(s => s.hasAttended).length;
    return { total, present, absent: total - present, rate: total > 0 ? ((present / total) * 100).toFixed(1) : 0 };
  }, [students]);

  if (loading) return <div className="min-h-screen bg-[#F4F7FE] flex items-center justify-center font-['Space_Grotesk'] text-indigo-600 font-bold animate-pulse">Initializing SPECTRUM...</div>;

  return (
    <div className="min-h-screen bg-[#F4F7FE] text-[#2B3674] font-['Space_Grotesk'] flex flex-col lg:flex-row p-4 lg:p-6 gap-6">
      
      {/* --- Sidebar --- */}
      <aside className="w-80 bg-[#111C44] rounded-[2.5rem] p-8 shadow-2xl hidden lg:flex flex-col text-white relative overflow-hidden">
        <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/10 rounded-full blur-3xl -mr-16 -mt-16"></div>
        <div className="flex items-center gap-4 mb-12 border-b border-white/10 pb-8">
          <div className="w-12 h-12 bg-white/10 rounded-2xl flex items-center justify-center backdrop-blur-md">
            <FiCommand className="text-white text-2xl" />
          </div>
          <div>
            <h1 className="text-xl font-bold tracking-tight">SPECTRUM</h1>
            <p className="text-[10px] text-indigo-300 font-bold uppercase tracking-[0.2em]">ECE Association</p>
          </div>
        </div>

        <nav className="space-y-4 flex-1">
          <button className="w-full flex items-center gap-4 px-6 py-4 rounded-2xl bg-white/10 text-white font-bold transition-all"><FiLayers /> Dashboard</button>
          <button className="w-full flex items-center gap-4 px-6 py-4 rounded-2xl text-white/50 font-bold hover:bg-white/5"><FiUsers /> Registry</button>
          <button className="w-full flex items-center gap-4 px-6 py-4 rounded-2xl text-white/50 font-bold hover:bg-white/5"><FiActivity /> Statistics</button>
        </nav>

        <div className="p-6 bg-white/5 rounded-3xl border border-white/10">
          <p className="text-xs text-indigo-300 mb-2 flex items-center gap-2"><FiClock /> System Time</p>
          <p className="text-2xl font-bold font-mono">{currentTime.toLocaleTimeString([], { hour12: false })}</p>
        </div>
      </aside>

      {/* --- Main Content --- */}
      <main className="flex-1 flex flex-col gap-8 min-w-0">
        <header className="bg-white rounded-[2rem] p-4 flex flex-col md:flex-row items-center justify-between gap-4 shadow-sm border border-white/50">
          <div className="flex items-center gap-3 px-4">
             <FiServer className="text-indigo-600" />
             <span className="text-sm font-bold">MCET Network Status: </span>
             <span className="flex items-center gap-1.5 text-emerald-500 font-bold text-sm">
                <span className="w-2 h-2 bg-emerald-500 rounded-full animate-ping"></span> Active
             </span>
          </div>
          
          <div className="flex items-center gap-3 w-full md:w-auto">
            <div className="relative flex-1">
              <FiSearch className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" />
              <input type="text" placeholder="Filter roll or name..." value={search} onChange={(e) => setSearch(e.target.value)} className="w-full bg-[#F4F7FE] border-none rounded-xl py-3 pl-12 pr-4 text-sm outline-none ring-2 ring-transparent focus:ring-indigo-100 transition-all" />
            </div>
            <button onClick={exportToPDF} className="flex items-center gap-2 px-6 py-3 bg-[#111C44] text-white rounded-xl text-xs font-bold hover:bg-indigo-900 transition-all">
              <FiFileText /> Export PDF
            </button>
            <button onClick={loadUsers} className="p-3 bg-white border border-slate-100 rounded-xl hover:bg-slate-50 text-indigo-600"><FiRefreshCw /></button>
          </div>
        </header>

        {/* Stats Section */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          <StatCard label="Total Registered" value={stats.total} icon={<FiUsers />} color="bg-indigo-600" />
          <StatCard label="Verified Presence" value={stats.present} icon={<FiCheckCircle />} color="bg-emerald-500" />
          <StatCard label="Absence Log" value={stats.absent} icon={<FiXCircle />} color="bg-rose-500" />
          <StatCard label="Attendance Yield" value={`${stats.rate}%`} icon={<FiActivity />} color="bg-orange-500" />
        </div>

        {/* Registry Table */}
        <div className="bg-white rounded-[2.5rem] shadow-xl p-8 border border-white overflow-hidden flex flex-col">
          <div className="flex items-center justify-between mb-8">
            <h2 className="text-2xl font-black flex items-center gap-3">
              Registry Feed <FiShield className="text-indigo-600 text-lg opacity-30" />
            </h2>
            <select 
              value={statusFilter} 
              onChange={(e) => setStatusFilter(e.target.value)} 
              className="bg-[#F4F7FE] border-none rounded-xl px-4 py-2 text-xs font-bold outline-none cursor-pointer"
            >
              <option value="all">Display All</option>
              <option value="present">Verified Only</option>
              <option value="absent">Pending Only</option>
            </select>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead>
                <tr className="border-b border-slate-50">
                  <th className="pb-6 text-[10px] font-black text-[#A3AED0] uppercase tracking-[0.2em]">Student Identity</th>
                  <th className="pb-6 text-[10px] font-black text-[#A3AED0] uppercase tracking-[0.2em]">Roll Index</th>
                  <th className="pb-6 text-[10px] font-black text-[#A3AED0] uppercase tracking-[0.2em] text-center">Status</th>
                  <th className="pb-6 text-[10px] font-black text-[#A3AED0] uppercase tracking-[0.2em] text-right">Operations</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-50/50">
                {filteredStudents.map((student) => (
                  <tr key={student._id} className="group hover:bg-[#F4F7FE]/50 transition-all duration-200">
                    <td className="py-6">
                      <div className="flex items-center gap-4">
                        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-50 to-blue-50 flex items-center justify-center font-black text-indigo-600 border border-indigo-100">
                          {student.name.charAt(0)}
                        </div>
                        <div>
                          <p className="font-bold text-[#2B3674]">{student.name}</p>
                          <p className="text-[10px] text-[#A3AED0] font-bold uppercase tracking-widest">{student.className}</p>
                        </div>
                      </div>
                    </td>
                    <td className="py-6">
                      <span className="font-mono text-xs font-black text-indigo-500 tracking-tighter">{student.rollNo}</span>
                    </td>
                    <td className="py-6 text-center">
                      <span className={`px-4 py-2 rounded-xl text-[10px] font-black uppercase tracking-wider shadow-sm border ${
                        student.hasAttended ? 'bg-emerald-50 text-emerald-600 border-emerald-100' : 'bg-rose-50 text-rose-600 border-rose-100'
                      }`}>
                        {student.hasAttended ? 'Verified' : 'Pending'}
                      </span>
                    </td>
                    <td className="py-6 text-right">
                      <button onClick={() => { setEditingStudent(student._id); setEditingStatus(student.hasAttended ? "present" : "absent"); }} className="p-3 hover:bg-indigo-50 rounded-2xl text-slate-400 hover:text-indigo-600 transition-all">
                        <FiEdit2 size={16} />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </main>

      {/* --- Quick Update Overlay --- */}
      {editingStudent && (
        <div className="fixed inset-0 bg-[#0B1437]/40 backdrop-blur-md z-50 flex items-center justify-center p-6">
          <div className="bg-white rounded-[3rem] p-10 w-full max-w-sm shadow-2xl animate-in zoom-in-95">
             <h3 className="text-xl font-black mb-2">Modify Status</h3>
             <p className="text-sm text-[#A3AED0] mb-8 font-medium">Update student verification status.</p>
             <div className="flex gap-4 mb-8">
                <button onClick={() => setEditingStatus("present")} className={`flex-1 py-4 rounded-2xl border-2 flex flex-col items-center gap-2 transition-all ${editingStatus === 'present' ? 'border-emerald-500 bg-emerald-50 text-emerald-600' : 'border-slate-50 opacity-40'}`}>
                  <FiCheckCircle size={20} /> <span className="text-[10px] font-black uppercase">Present</span>
                </button>
                <button onClick={() => setEditingStatus("absent")} className={`flex-1 py-4 rounded-2xl border-2 flex flex-col items-center gap-2 transition-all ${editingStatus === 'absent' ? 'border-rose-500 bg-rose-50 text-rose-600' : 'border-slate-50 opacity-40'}`}>
                  <FiXCircle size={20} /> <span className="text-[10px] font-black uppercase">Absent</span>
                </button>
             </div>
             <div className="flex gap-3">
                <button onClick={() => setEditingStudent(null)} className="flex-1 py-4 bg-slate-100 text-slate-500 rounded-2xl font-bold text-sm">Cancel</button>
                <button onClick={() => updateAttendance(editingStudent, editingStatus)} className="flex-[2] py-4 bg-indigo-600 text-white rounded-2xl font-bold text-sm shadow-lg shadow-indigo-100">Update Securely</button>
             </div>
          </div>
        </div>
      )}
    </div>
  );
};

const StatCard = ({ label, value, icon, color }) => (
  <div className="bg-white p-6 rounded-[2.5rem] shadow-sm flex items-center gap-5 border border-white group hover:shadow-xl transition-all">
    <div className={`w-14 h-14 rounded-2xl ${color} text-white flex items-center justify-center text-2xl shadow-lg transition-transform group-hover:rotate-12`}>
      {icon}
    </div>
    <div>
      <p className="text-[10px] font-black text-[#A3AED0] uppercase tracking-widest mb-1">{label}</p>
      <p className="text-2xl font-black text-[#2B3674]">{value}</p>
    </div>
  </div>
);

export default AdminDashboard;